/**
 * The sprite asset contract (issue #93, art pipeline 1/6).
 *
 * Two manifest shapes live here, and both parsers are deliberately kept free of
 * React, DOM and `import.meta` so that `scripts/normalize-sprites.ts` can import
 * them under `tsx` as well:
 *
 * - **source manifest** (`scripts/sprite-sources/<animal>.json`) — hand-written.
 *   Says where the raw art came from, how its files or sheet cells map onto our
 *   pose names, and how fast each pose plays.
 * - **sprite manifest** (`public/sprites/<animal>/manifest.json`) — generated by
 *   the normalizer, checked in, and imported by the app. Frame size and file
 *   naming in here are the contract every later art issue builds on; changing
 *   them means re-running the normalizer for every animal.
 */

/** Pose names the game knows about. Every animal must provide all four. */
export const REQUIRED_POSES = ['idle', 'move', 'hurt', 'celebrate'] as const;

export type PoseName = (typeof REQUIRED_POSES)[number];

/** Frame sizes the pipeline supports. 96 is what we ship; 64 is kept legal so a
 * later pack of genuinely low-res pixel art doesn't need a contract change. */
export const ALLOWED_FRAME_SIZES = [64, 96] as const;

export type FrameSize = (typeof ALLOWED_FRAME_SIZES)[number];

export type SpritePose = {
  /** Frame files, in play order, relative to the manifest's `basePath`. */
  readonly frames: readonly string[];
  /** Frames per second. */
  readonly fps: number;
  /** Loop forever, or hold the last frame once it is reached. */
  readonly loop: boolean;
};

export type SpriteCredit = {
  readonly pack: string;
  readonly author: string;
  readonly url: string;
  readonly downloadUrl: string;
  readonly license: string;
  readonly licenseUrl: string;
};

export type SpriteManifest = {
  readonly animal: string;
  readonly displayName: string;
  /** Every frame file is exactly `frameSize` x `frameSize`, true alpha. */
  readonly frameSize: FrameSize;
  /** Path of the frame directory, relative to the deployed site root, no slashes on either end. */
  readonly basePath: string;
  readonly credit: SpriteCredit;
  readonly poses: Readonly<Record<string, SpritePose>>;
};

/** Where a source manifest's raw art comes from: a directory of PNGs... */
export type SpriteSourceDir = {
  readonly kind: 'dir';
  /** Repo-relative default; overridable with `--src` on the command line. */
  readonly path: string;
};

/** ...or one sprite sheet cut into a fixed grid, read left-to-right, top-to-bottom. */
export type SpriteSourceSheet = {
  readonly kind: 'sheet';
  readonly path: string;
  readonly frameWidth: number;
  readonly frameHeight: number;
  readonly columns: number;
};

export type SpriteSource = SpriteSourceDir | SpriteSourceSheet;

export type SpriteSourcePose = {
  /** File names for a `dir` source, zero-based cell indices for a `sheet` source. */
  readonly frames: readonly (string | number)[];
  readonly fps: number;
  readonly loop: boolean;
};

export type SpriteSourceManifest = {
  readonly animal: string;
  readonly displayName: string;
  readonly frameSize: FrameSize;
  readonly source: SpriteSource;
  /** Optional license file to copy next to the normalized frames. */
  readonly licenseFile?: string;
  readonly credit: SpriteCredit;
  readonly poses: Readonly<Record<string, SpriteSourcePose>>;
};

class ManifestError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ManifestError';
  }
}

function fail(where: string, message: string): never {
  throw new ManifestError(`${where}: ${message}`);
}

function asRecord(value: unknown, where: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    fail(where, `expected an object, got ${Array.isArray(value) ? 'an array' : typeof value}`);
  }
  return value as Record<string, unknown>;
}

function str(record: Record<string, unknown>, key: string, where: string): string {
  const value = record[key];
  if (typeof value !== 'string' || value.length === 0) {
    fail(`${where}.${key}`, `expected a non-empty string, got ${JSON.stringify(value)}`);
  }
  return value;
}

function positiveInt(record: Record<string, unknown>, key: string, where: string): number {
  const value = record[key];
  if (typeof value !== 'number' || !Number.isInteger(value) || value <= 0) {
    fail(`${where}.${key}`, `expected a positive integer, got ${JSON.stringify(value)}`);
  }
  return value;
}

function bool(record: Record<string, unknown>, key: string, where: string): boolean {
  const value = record[key];
  if (typeof value !== 'boolean') {
    fail(`${where}.${key}`, `expected a boolean, got ${JSON.stringify(value)}`);
  }
  return value;
}

function frameSize(record: Record<string, unknown>, where: string): FrameSize {
  const value = record.frameSize;
  if (!ALLOWED_FRAME_SIZES.includes(value as FrameSize)) {
    fail(
      `${where}.frameSize`,
      `expected one of ${ALLOWED_FRAME_SIZES.join(', ')}, got ${JSON.stringify(value)}`,
    );
  }
  return value as FrameSize;
}

function fps(record: Record<string, unknown>, where: string): number {
  const value = record.fps;
  if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0 || value > 60) {
    fail(`${where}.fps`, `expected a number in (0, 60], got ${JSON.stringify(value)}`);
  }
  return value;
}

function credit(value: unknown, where: string): SpriteCredit {
  const record = asRecord(value, where);
  return {
    pack: str(record, 'pack', where),
    author: str(record, 'author', where),
    url: str(record, 'url', where),
    downloadUrl: str(record, 'downloadUrl', where),
    license: str(record, 'license', where),
    licenseUrl: str(record, 'licenseUrl', where),
  };
}

function poseNames(poses: Record<string, unknown>, where: string): string[] {
  const names = Object.keys(poses);
  const missing = REQUIRED_POSES.filter((pose) => !names.includes(pose));
  if (missing.length > 0) {
    fail(`${where}.poses`, `missing required pose(s): ${missing.join(', ')}`);
  }
  return names;
}

/**
 * Validate a generated sprite manifest — the shape the app reads. Throws with a
 * path-prefixed message naming the offending field.
 */
export function parseSpriteManifest(value: unknown): SpriteManifest {
  const where = 'manifest';
  const record = asRecord(value, where);
  const animal = str(record, 'animal', where);
  const basePath = str(record, 'basePath', where);
  if (basePath.startsWith('/') || basePath.endsWith('/')) {
    fail(`${where}.basePath`, `must not start or end with "/", got ${JSON.stringify(basePath)}`);
  }

  const posesRecord = asRecord(record.poses, `${where}.poses`);
  const poses: Record<string, SpritePose> = {};
  for (const name of poseNames(posesRecord, where)) {
    const poseWhere = `${where}.poses.${name}`;
    const pose = asRecord(posesRecord[name], poseWhere);
    const frames = pose.frames;
    if (!Array.isArray(frames) || frames.length === 0) {
      fail(`${poseWhere}.frames`, 'expected a non-empty array of frame file names');
    }
    for (const [index, frame] of frames.entries()) {
      if (typeof frame !== 'string' || !frame.endsWith('.png')) {
        fail(
          `${poseWhere}.frames[${index}]`,
          `expected a .png file name, got ${JSON.stringify(frame)}`,
        );
      }
    }
    poses[name] = {
      frames: frames as string[],
      fps: fps(pose, poseWhere),
      loop: bool(pose, 'loop', poseWhere),
    };
  }

  const move = poses.move;
  if (move.frames.length < 4) {
    fail(`${where}.poses.move.frames`, `expected at least 4 frames, got ${move.frames.length}`);
  }

  return {
    animal,
    displayName: str(record, 'displayName', where),
    frameSize: frameSize(record, where),
    basePath,
    credit: credit(record.credit, `${where}.credit`),
    poses,
  };
}

/** Validate a hand-written source manifest — the normalizer's input. */
export function parseSpriteSourceManifest(value: unknown): SpriteSourceManifest {
  const where = 'source manifest';
  const record = asRecord(value, where);

  const sourceWhere = `${where}.source`;
  const sourceRecord = asRecord(record.source, sourceWhere);
  const kind = sourceRecord.kind;
  let source: SpriteSource;
  if (kind === 'dir') {
    source = { kind: 'dir', path: str(sourceRecord, 'path', sourceWhere) };
  } else if (kind === 'sheet') {
    source = {
      kind: 'sheet',
      path: str(sourceRecord, 'path', sourceWhere),
      frameWidth: positiveInt(sourceRecord, 'frameWidth', sourceWhere),
      frameHeight: positiveInt(sourceRecord, 'frameHeight', sourceWhere),
      columns: positiveInt(sourceRecord, 'columns', sourceWhere),
    };
  } else {
    fail(`${sourceWhere}.kind`, `expected "dir" or "sheet", got ${JSON.stringify(kind)}`);
  }

  const posesRecord = asRecord(record.poses, `${where}.poses`);
  const poses: Record<string, SpriteSourcePose> = {};
  for (const name of poseNames(posesRecord, where)) {
    const poseWhere = `${where}.poses.${name}`;
    const pose = asRecord(posesRecord[name], poseWhere);
    const frames = pose.frames;
    if (!Array.isArray(frames) || frames.length === 0) {
      fail(`${poseWhere}.frames`, 'expected a non-empty array of frames');
    }
    for (const [index, frame] of frames.entries()) {
      const frameWhere = `${poseWhere}.frames[${index}]`;
      if (source.kind === 'dir') {
        if (typeof frame !== 'string' || frame.length === 0) {
          fail(frameWhere, `a "dir" source needs file names, got ${JSON.stringify(frame)}`);
        }
      } else if (typeof frame !== 'number' || !Number.isInteger(frame) || frame < 0) {
        fail(frameWhere, `a "sheet" source needs cell indices, got ${JSON.stringify(frame)}`);
      }
    }
    poses[name] = {
      frames: frames as (string | number)[],
      fps: fps(pose, poseWhere),
      loop: bool(pose, 'loop', poseWhere),
    };
  }

  if (poses.move.frames.length < 4) {
    fail(
      `${where}.poses.move.frames`,
      `expected at least 4 frames, got ${poses.move.frames.length}`,
    );
  }

  const licenseFile = record.licenseFile;
  if (licenseFile !== undefined && typeof licenseFile !== 'string') {
    fail(`${where}.licenseFile`, `expected a string, got ${JSON.stringify(licenseFile)}`);
  }

  return {
    animal: str(record, 'animal', where),
    displayName: str(record, 'displayName', where),
    frameSize: frameSize(record, where),
    source,
    ...(licenseFile === undefined ? {} : { licenseFile }),
    credit: credit(record.credit, `${where}.credit`),
    poses,
  };
}
